site_name: OmAgent
site_url: https://om-ai-lab.github.io/OmAgentDocs/
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/om-ai-lab/OmAgent
repo_name: om-ai-lab/OmAgent
markdown_extensions:
  - meta # 用于在Markdown文件中添加元数据
  - toc:
      permalink: true # 为标题添加永久链接
  - admonition # 支持警告、提示等特殊内容块
  - footnotes # 支持脚注功能
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
            - Home: index.md
            - Getting Started:
                - Introduction: getting_started/intro.md
                - Installation: getting_started/install.md
                - Quick Start: getting_started/quick_start.md
                # - Visualization and analysis: Getting Started/3_visual.md
            - Guides:
                # - Let the agent think:
                #     - More complex workflow: Guides/Let the agent think/1_workflow.md
                #     - Tools: Guides/Let the agent think/2_tool.md
                # - Let the agent remember:
                #     - Memory: Guides/Let the agent remember/1_memory.md
                - A Simple VQA Agent: Guides/simple_vqa.md
                - Let Agent Decide: Guides/outfit_with_switch.md
                - How To Loop: Guides/outfit_with_loop.md
                - Let Agent Remember: Guides/outfit_with_ltm.md
            - Core Concepts:
                # - Node:
                #     - Introduction: core_concepts/Node/intro.md
                #     - Configuration: core_concepts/Node/config.md
                #     - Build: core_concepts/Node/build.md
                - Workflow:
                    # - Introduction: core_concepts/Workflow/intro.md
                    # - Configuration: core_concepts/Workflow/config.md
                    # - Build: core_concepts/Workflow/build.md
                    - Workflow: core_concepts/Workflow/workflow.md
                    - Task: core_concepts/Workflow/task.md
                    - Worker: core_concepts/Workflow/worker.md
                - Models:
                    # - Introduction: core_concepts/Models/intro.md
                    # - Configuration: core_concepts/Models/config.md
                    # - Build: core_concepts/Models/build.md
                    - Large Languages Models: core_concepts/Models/llms.md
                - Tool:
                    - Introduction: core_concepts/Tool/intro.md
                    # - Configuration: core_concepts/Tool/config.md
                    # - Build: core_concepts/Tool/build.md
                - Memory:
                    - Introduction: core_concepts/Memory/intro.md
                    # - Configuration: core_concepts/Memory/config.md
                    # - Build: core_concepts/Memory/build.md
                - Clients:
                    # - Introduction: core_concepts/Clients/intro.md
                    # - Configuration: core_concepts/Clients/config.md
                    # - Build: core_concepts/Clients/build.md
                    - Client Types: core_concepts/Clients/client.md
                    - How to use app: core_concepts/Clients/app.md
                - Container: core_concepts/container.md
                - Register Modules: core_concepts/registry.md
                - Running In Debug Mode: core_concepts/debug.md
        # - locale: zh
        #   name: 中文
        #   build: true
        #   nav:
        #     - 首页: index.md
        #     - 开始:
        #         - 快速开始: Getting Started/1_quick_start.md
        #         - 连接设备: Getting Started/2_devices.md
        #         - 可视化与分析: Getting Started/3_visual.md
        #     - 指南:
        #         - 让Agent思考:
        #             - 更复杂的流程: Guides/Let the agent think/1_workflow.md
        #             - 使用工具: Guides/Let the agent think/2_tool.md
        #         - 让Agent记住:
        #             - 记忆: Guides/Let the agent remember/1_memory.md
        #     - 核心概念:
        #         - Node:
        #             - 介绍: core_concepts/Node/intro.md
        #             - 配置: core_concepts/Node/config.md
        #             - 构建: core_concepts/Node/build.md
        #         - Workflow:
        #             - 介绍: core_concepts/Workflow/intro.md
        #             - 配置: core_concepts/Workflow/config.md
        #             - 构建: core_concepts/Workflow/build.md
        #         - Models:
        #             - 介绍: core_concepts/Models/intro.md
        #             - 配置: core_concepts/Models/config.md
        #             - 构建: core_concepts/Models/build.md
        #         - Tool:
        #             - 介绍: core_concepts/Tool/intro.md
        #             - 配置: core_concepts/Tool/config.md
        #             - 构建: core_concepts/Tool/build.md
        #         - Memory:
        #             - 介绍: core_concepts/Memory/intro.md
        #             - 配置: core_concepts/Memory/config.md
        #             - 构建: core_concepts/Memory/build.md
        #         - Clients:
        #             - 介绍: core_concepts/Clients/intro.md
        #             - 配置: core_concepts/Clients/config.md
        #             - 构建: core_concepts/Clients/build.md
  - search: # 搜索
      lang:
        - en
        - zh
      separator: '[\s\-\.]+' # 分词分隔符
extra:
  social: # 社交账号
    - icon: fontawesome/brands/github
      link: https://github.com/om-ai-lab/OmAgent
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/OmAI_lab
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CtmCgXZB
  static_files:
    - assets/images/*
  version:
    provider: mike
